server:
  port: ${PORT:8081}

spring:
  application:
    name: APIService
  logging:
    level:
      org.springframework: WARN
      org.hibernate: WARN
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/books?currentSchema=public
    username: postgres
    password: 12345
  liquibase:
      change-log: classpath:liquabase/changelog-master.xml

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

ribbon:
  eureka:
    enabled: true
