server:
  port: ${PORT:8081}

spring:
  application:
    name: APIService
  logging:
    level:
      org.springframework: WARN
      org.hibernate: WARN

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

ribbon:
  eureka:
    enabled: true
