version: "3"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    networks:
      - kafka_network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000


  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - 9092:9092
    networks:
      - kafka_network
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1


  postgres:
    image: debezium/postgres:11
    ports:
      - 5432:5432
    networks:
      - kafka_network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 3s
      timeout: 5s
      retries: 5


  # DISCOVERY SERVICE
  discovery:
    build:
      context: ./DiscoveryService
      dockerfile: Dockerfile
    ports:
      - 8761:8761
    environment:
      - DISCOVERY_URL=http://discovery:8761

  # SERVICES
  apiservice:
    build:
      context: ./APIService
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DISCOVERY_URL=http://discovery:8761
    links:
      - discovery
    depends_on:
      - discovery

  apiservice_two:
    build:
      context: ./APIService
      dockerfile: Dockerfile
    ports:
     - 9080:8080
    environment:
      - DISCOVERY_URL=http://discovery:8761
    links:
      - discovery
    depends_on:
      - discovery

  adminservice:
    build:
      context: ./AdminService
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    environment:
      - DISCOVERY_URL=http://discovery:8761
    links:
      - discovery
    depends_on:
      - discovery

  adminservice_two:
    build:
      context: ./AdminService
      dockerfile: Dockerfile
    ports:
      - 9081:8081
    environment:
      - DISCOVERY_URL=http://discovery:8761
    links:
      - discovery
    depends_on:
      - discovery

  # API GATEWAY
  gateway:
    build:
      context: ./APIGateway
      dockerfile: Dockerfile
    ports:
      - 8765:8765
    environment:
      - DISCOVERY_URL=http://discovery:8761
    links:
      - discovery
      - adminservice
      - adminservice_two
      - apiservice
      - apiservice_two
    depends_on:
      - discovery


  networks:
    kafka_network:
      name: broker_network
